---
title       : Developing Data Products - BMI
framework   : revealjs     
highlighter : highlight.js  
hitheme     : default       
widgets     : []           
mode        : selfcontained 
knit        : slidify::knit2slides
---


## Developing Data Products - BMI

**Coursera Course Project**

Author <span style="color:darkblue; font-weight:bold">DSG.</span>


--- .class #id 

## Why Body Mass Index

The reason why I chose to implement a Body Mass Indicator is because I think it is an important parameter for a human being, specially in today's world, where general diets are not as healthy as it should be. Besides that, during the process of evaluation of this project, why not to check your BMI?


--- .class #id 

## BMI Formula Explanation

The BMI is a value derived from the mass (weight) and height of an individual. The BMI is defined as the body mass divided by the square of the body height (weight/height^2) and is universally expressed in units of kg/m2. 

If the BMI value is lower than 18.5 the conclusion will be that the value is Low, if it is between 18.51 and 24.99 the conclusion will be that the value is Normal and if it is 25 or higher the conclusion will be that the value is Overweight


--- .class #id 

## BMI Plot by diet and exercise

BMI US Study

```{r,echo=FALSE}
setwd('D:/Otros/Cursos y formacion/Coursera/Data Scientist/9-Developing Data Products/course_project/slidify/Dev Data Products')
bmi_data<-read.csv('bmi_data.csv', sep=';')
names(bmi_data)<-c('diet','min_ex','body','BMI')
require(ggplot2)
ggplot(bmi_data, aes(x=min_ex, y=BMI, colour=diet)) + geom_point(size=2)+
    theme(axis.text.x=element_text(angle=90, hjust=1))+
    scale_x_continuous('Minutes of exercies per week')
```

--- .class #id 

## Results

Previous plot represents information about people in the US regarding to their BMI. The study is about their final BMI  depending on whether they exercise and diet.

<span style="color:green; font-weight:bold">The result is that to have a healthy BMI it is more important to do exercise than diet.</span>

